export const COMMENT_LIKE_REQUEST = "COMMENT_LIKE_REQUEST";
export const COMMENT_LIKE_SUCCESS = "COMMENT_LIKE_SUCCESS";
export const COMMENT_LIKE_FAIL = "COMMENT_LIKE_FAIL";
export const COMMENT_LIKE_RESET = "COMMENT_LIKE_RESET";

export const COMMENT_UNLIKE_REQUEST = "COMMENT_UNLIKE_REQUEST";
export const COMMENT_UNLIKE_SUCCESS = "COMMENT_UNLIKE_SUCCESS";
export const COMMENT_UNLIKE_FAIL = "COMMENT_UNLIKE_FAIL";
export const COMMENT_UNLIKE_RESET = "COMMENT_UNLIKE_RESET";
