export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_CREATE_RESET = "POST_CREATE_RESET";

export const POST_COMMENT_ADD_REQUEST = "POST_COMMENT_ADD_REQUEST";
export const POST_COMMENT_ADD_SUCCESS = "POST_COMMENT_ADD_SUCCESS";
export const POST_COMMENT_ADD_FAIL = "POST_COMMENT_ADD_FAIL";
export const POST_COMMENT_ADD_RESET = "POST_COMMENT_ADD_RESET";

export const POST_LIKE_ADD_REQUEST = "POST_LIKE_ADD_REQUEST";
export const POST_LIKE_ADD_SUCCESS = "POST_LIKE_ADD_SUCCESS";
export const POST_LIKE_ADD_FAIL = "POST_LIKE_ADD_FAIL";
export const POST_LIKE_ADD_RESET = "POST_LIKE_ADD_RESET";

export const POST_UNLIKE_ADD_REQUEST = "POST_UNLIKE_ADD_REQUEST";
export const POST_UNLIKE_ADD_SUCCESS = "POST_UNLIKE_ADD_SUCCESS";
export const POST_UNLIKE_ADD_FAIL = "POST_UNLIKE_ADD_FAIL";
export const POST_UNLIKE_ADD_RESET = "POST_UNLIKE_ADD_RESET";

export const POST_REPOST_ADD_REQUEST = "POST_REPOST_ADD_REQUEST";
export const POST_REPOST_ADD_SUCCESS = "POST_REPOST_ADD_SUCCESS";
export const POST_REPOST_ADD_FAIL = "POST_REPOST_ADD_FAIL";
export const POST_REPOST_ADD_RESET = "POST_REPOST_ADD_RESET";

export const POST_UNREPOST_ADD_REQUEST = "POST_UNREPOST_ADD_REQUEST";
export const POST_UNREPOST_ADD_SUCCESS = "POST_UNREPOST_ADD_SUCCESS";
export const POST_UNREPOST_ADD_FAIL = "POST_UNREPOST_ADD_FAIL";
export const POST_UNREPOST_ADD_RESET = "POST_UNREPOST_ADD_RESET";
